---
- name: create db on server (if db not exist)
  mysql_db: name={{ dbname }} state=present login_unix_socket=/var/run/mysqld/mysqld.sock

- name: Create user for db {{ dbname }}
  mysql_user: name={{ dbuser }} host={{ item }} password={{ dbpassword }} priv={{ dbname }}.*:ALL state=present login_unix_socket=/var/run/mysqld/mysqld.sock
  with_items:
        - "{{ ansible_hostname }}"
        - 127.0.0.1
        - localhost
        - "{{ myip }}"
