---
#####
# Usage:
#   ansible-playbook minisite.yml -i minisite -vv
#####
- hosts: jobscapa.org
  vars:
   hname: jobscapaorg
   siteurl: jobscapa.org
   myip: 148.251.52.146
###to make passwd use: mkpasswd --method=SHA-256 [PASSWD]
   upassw: $5$2dZwRVvj$3jmtLeHmZBvmqcEa8yKQhB/DTqjfPlyzV.cnq7rADP9
###MySQL user and db settings
   dbname: capadb
   dbuser: capausr
   dbpassword: oxM3DbybGCWT
###Monitorix pass 8 charset max!!!!
   monpasswd: PxnF38Ll

   phpmyadmin_version: 4.4.15

#set pakage def variables

  vars_files:
   - roles/geerlingguy.php/vars/jm.yml
   - roles/geerlingguy.apache/vars/jm.yml

##configure repos, install system soft, setup system settings


  roles:
##added repos
    - { role: geerlingguy.repo-epel }
    - { role: geerlingguy.repo-remi }
    - { role: repo-rpmforge }
##install system software and tuning system parm
    - { role: preconf }
###make separate vars!!!
    - { role: geerlingguy.ntp }
###using for CentOS only!
    - { role: azmelanar.sysctl }
###added user for site
    - { role: vhostuser }
###install apache web server
    - { role: geerlingguy.apache }
###Oracle Java for elasticsearch
    - { role: oraclejava }
###Install end configure elasticsearch
    - { role: geerlingguy.elasticsearch }
###Install end configure Percona server
    - { role: ben.mildren.percona_mysql, percona_mysql_include_tokudb_variables: true, percona_mysql_include_jemalloc_variables: true }
##Create db on mysql server
    - { role: mysqluser }
###intall php
    - { role: geerlingguy.php }
##Log rotate
    - { role: logrotate }
##fail2ban sshd role 
#    - { role: fail2ban }
##maldet install
    - { role: maldet }
##monitorix configuratin
    - { role: monitorix }
##PMA
    - { role: pma }
##clone from repos
    - { role: hgclone }
